### ISSUE TITLE
nome da cidade

### ISSUE THREAD

**Issue by luciostuder** [lusanmanso/lusanmanso.github.io#1]
- Substituir pelo nome da cidade. o mesmo para o title
https://github.com/lusanmanso/lusanmanso.github.io/blob/93a4bd1b4b41aa843aad2b0d81a796d60041829b/lab2/index.html#L9

- reduzir o tamanho da imagem de madrid. editar ocm paint, reduzir para ~300px largura, e substituir

**Comment by lusanmanso** [comment]
Imagem de Vitoria-Gasteiz? Done.
